name: "Build python wheels"

on:
  workflow_call:
    inputs:
      CIBW_BUILD:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      VCPKG_BINARY_SOURCES: ${{ vars.VCPKG_BINARY_SOURCES }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      # only required until R2 supports CRC64NVME checksums
      # https://community.cloudflare.com/t/an-error-occurred-internalerror-when-calling-the-putobject-operation/764905/11
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install vcpkg
        run: ./vcpkg.sh

      - uses: pypa/cibuildwheel@v3.1
        name: Build wheel
        env:
          # install openmp stuff for mac
          CIBW_BEFORE_ALL_MACOS: >
              curl -O https://mac.r-project.org/openmp/openmp-19.1.0-darwin20-Release.tar.gz &&
              sudo tar fvxz openmp-19.1.0-darwin20-Release.tar.gz -C /
          # install aws cli for vcpkg caching
          CIBW_BEFORE_ALL_LINUX: >
              yum -y install curl zip unzip tar &&
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
              unzip awscliv2.zip &&
              ./aws/install

          CIBW_BUILD: ${{ inputs.CIBW_BUILD }}
          CIBW_ENVIRONMENT_PASS_LINUX: VCPKG_BINARY_SOURCES AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ENDPOINT_URL AWS_REQUEST_CHECKSUM_CALCULATION AWS_RESPONSE_CHECKSUM_VALIDATION

      # save artifacts for testing
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
