name: "General checks: Lints, Tests, Types"

on:
  workflow_call:

jobs:
  # check python formatting
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/ruff-action@v3
        name: Ruff

  # check python typing
  types:
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: ${{ vars.VCPKG_BINARY_SOURCES }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      # only required until R2 supports CRC64NVME checksums
      # https://community.cloudflare.com/t/an-error-occurred-internalerror-when-calling-the-putobject-operation/764905/11
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install vcpkg
        run: ./vcpkg.sh
      - name: Install the project
        run: uv sync --dev --verbose --all-extras
      - name: Copy stubs into place
        run: cp -r .venv/lib/python$(cat .python-version)/site-packages/gtsam/_core python/gtsam
      - name: Run basedpyright
        run: uv run basedpyright

  # check cpp formatting
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: jidicula/clang-format-action@v4.14.0
      name: Clang-Format
      with:
        clang-format-version: '20'

  # run tests on both mac and ubuntu, on newest/oldest python versions
  test:
    runs-on: ${{ matrix.os }}
    env:
      UV_NO_EDITABLE: true
      VCPKG_BINARY_SOURCES: ${{ vars.VCPKG_BINARY_SOURCES }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      # only required until R2 supports CRC64NVME checksums
      # https://community.cloudflare.com/t/an-error-occurred-internalerror-when-calling-the-putobject-operation/764905/11
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.11"
          - "3.14"
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install vcpkg
        run: ./vcpkg.sh
      - name: Install the project
        run: uv sync --dev --verbose

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Run tests
        run: uv run pytest -v
